# Generated by Django 4.0.2 on 2022-02-15 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rated', '0002_profile_user_projects_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('usability_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('content_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('average', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rated.projects')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
