# Generated by Django 4.0.2 on 2022-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rated', '0003_alter_projects_description_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('bio', models.CharField(max_length=200, null=True)),
                ('pic', models.URLField()),
                ('projects', models.TextField()),
            ],
        ),
    ]
