# Generated by Django 4.0.2 on 2022-02-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rated', '0004_profileapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileAPI',
        ),
    ]
